"""create insurance table

Revision ID: 5631cfb562a5
Revises: ffdc0a98111c
Create Date: 2022-04-13 18:45:06.989071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5631cfb562a5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insurance_co', sa.String(length=100), nullable=False),
    sa.Column('subscriber_num', sa.String(length=30), nullable=False),
    sa.Column('group_num', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance')
    # ### end Alembic commands ###
